# This is a basic workflow to build robot code.
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This grabs the WPILib docker container
    container:
      image: wpilib/roborio-cross-ubuntu:2025-22.04
      options: --dns=1.1.1.1 --dns=8.8.8.8
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    #enter y2025 and setup gradlew permission
    - name: Enter y2025 and Setup
      run: |
        chmod +x gradlew          # gradlew in y2025
        git config --global --add safe.directory $GITHUB_WORKSPACE/y2025
        
    #clean cache
    - name: Clean-SpotlessApply
      run: |
        ./gradlew spotlessApply
      
    # compile
    - name: Compile and Test
      run: |
        ./gradlew build